name: Build and deploy Doxygen documentation

on:
  push:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    # Build Doxygen documentation
    # mattnotmitt/doxygen-action
    # https://github.com/marketplace/actions/doxygen-action

    # Deploy Doxygen documentation
    # peaceiris/actions-gh-pages
    # https://github.com/peaceiris/actions-gh-pages

